(asdf:defsystem "cl-problem-solving"
  :version "1.0.0"
  :author "Nicolas Occis"
  :maintainer "Nicolas Occis"
  :license "MIT"
  :homepage "https://github.com/occisn/cl-problem-solving"
  :description "Problem solving in Common Lisp"
  :depends-on ()
  :serial t ; load files in order
  ;; Compilation policy for every file of the system, set in one place.
  ;;
  ;; Beware: PROCLAIM is global and permanent.  It is not undone when this
  ;; system has finished compiling, so the setting below stays in force for
  ;; the rest of the session and applies to every other system compiled
  ;; afterwards in the same image.
  :around-compile (lambda (next)
                    (proclaim '(optimize (debug 0) 
                                (safety 0)
                                (speed 3)))
                    (funcall next))
  :components ((:module "src"
                :serial t
                :components
                ((:file "package")
                 (:file "project-euler-001")
                 (:file "project-euler-002")
                 (:file "project-euler-003")
                 (:file "project-euler-004")
                 (:file "project-euler-005")
                 (:file "project-euler-006")
                 (:file "project-euler-007")
                 (:file "project-euler-008")
                 (:file "project-euler-008__variants")
                 (:file "project-euler-009")
                 (:file "project-euler-010")
                 (:file "project-euler-010__variants")
                 (:file "project-euler-011")
                 (:file "project-euler-012")
                 (:file "project-euler-012__variants")
                 (:file "project-euler-013")
                 (:file "project-euler-014")
                 (:file "project-euler-014__variants")
                 (:file "project-euler-015")
                 (:file "project-euler-015__variants")
                 (:file "project-euler-016")
                 (:file "project-euler-017")
                 (:file "project-euler-018")
                 (:file "project-euler-018__variants")
                 (:file "project-euler-019")
                 (:file "project-euler-020")
                 (:file "project-euler-021")
                 (:file "project-euler-022")
                 (:file "project-euler-023")
                 (:file "project-euler-024")
                 (:file "project-euler-025")
                 (:file "project-euler-025__variants")
                 (:file "project-euler-026")
                 (:file "project-euler-027")
                 (:file "project-euler-028")
                 (:file "project-euler-028__variants")
                 (:file "project-euler-029")
                 (:file "project-euler-030")
                 (:file "project-euler-031")
                 (:file "project-euler-031__variants")
                 (:file "project-euler-032")
                 (:file "project-euler-033")
                 (:file "project-euler-034")
                 (:file "project-euler-035")
                 (:file "project-euler-036")
                 (:file "project-euler-037")
                 (:file "project-euler-038")
                 (:file "project-euler-039")
                 (:file "project-euler-040")
                 (:file "project-euler-041")
                 (:file "project-euler-042")
                 (:file "project-euler-043")
                 (:file "project-euler-044")
                 (:file "project-euler-045")
                 (:file "project-euler-046")
                 (:file "project-euler-047")
                 (:file "project-euler-048")
                 (:file "project-euler-049")
                 (:file "project-euler-050")
                 (:file "project-euler-051")
                 (:file "project-euler-052")
                 (:file "project-euler-053")
                 (:file "project-euler-054")
                 (:file "project-euler-055")
                 (:file "project-euler-056")
                 (:file "project-euler-057")
                 (:file "project-euler-058")
                 (:file "project-euler-059")
                 (:file "project-euler-060")
                 (:file "project-euler-061")
                 (:file "project-euler-062")
                 (:file "project-euler-063")
                 (:file "project-euler-064")
                 (:file "project-euler-065")
                 (:file "project-euler-066")
                 (:file "project-euler-067")
                 (:file "project-euler-068")
                 (:file "project-euler-069")
                 (:file "project-euler-070")
                 (:file "project-euler-071")
                 (:file "project-euler-072")
                 (:file "project-euler-073")
                 (:file "project-euler-074")
                 (:file "project-euler-075")
                 (:file "project-euler-080")
                 (:file "project-euler-081")
                 (:file "project-euler-089")
                 (:file "project-euler-254")
                 (:file "project-euler-684")
                 (:file "ile-maths")
                 (:file "certificat")
                 (:file "fermat-library")
                 (:file "devil-calculator")
                 (:file "anecdotes-maths")
                 (:file "tupper")
                 ;;
                 (:file "main"))))
  :perform (load-op :after (op c)
                    (format t "~%Welcome in cl-problem-solving!~%~%")
                    (format t "Execute (cl-problem-solving:main) to solve all available problems at once.~%"))
  :in-order-to ((asdf:test-op (asdf:test-op :cl-problem-solving-tests))))
