;;;; Entry point: run every available solution in turn.

(in-package :cl-problem-solving)

(defun main ()
  "Print the answer to every problem solved in this system."
  (format t "Project Euler   1: ~a~%" (project-euler-001))
  (format t "Project Euler   2: ~a~%" (project-euler-002))
  (format t "Project Euler   3: ~a~%" (project-euler-003))
  (format t "Project Euler   4: ~a~%" (project-euler-004))
  (format t "Project Euler   5: ~a~%" (project-euler-005))
  (format t "Project Euler   6: ~a~%" (project-euler-006))
  (format t "Project Euler   7: ~a~%" (project-euler-007))
  (format t "Project Euler   8: ~a~%" (project-euler-008))
  (format t "Project Euler   9: ~a~%" (caar (project-euler-009)))
  (format t "Project Euler  10: ~a~%" (project-euler-010))
  (format t "Project Euler  11: ~a~%" (project-euler-011))
  (format t "Project Euler  12: ~a~%" (project-euler-012))
  (format t "Project Euler  13: ~a~%" (project-euler-013))
  (format t "Project Euler  14: ~a~%" (project-euler-014))
  (format t "Project Euler  15: ~a~%" (project-euler-015))
  (format t "Project Euler  16: ~a~%" (project-euler-016))
  (format t "Project Euler  17: ~a~%" (project-euler-017))
  (format t "Project Euler  18: ~a~%" (project-euler-018))
  (format t "Project Euler  19: ~a~%" (project-euler-019))
  (format t "Project Euler  20: ~a~%" (project-euler-020))
  (format t "Project Euler  21: ~a~%" (project-euler-021))
  (format t "Project Euler  22: ~a~%" (project-euler-022))
  (format t "Project Euler  23: ~a~%" (project-euler-023))
  (format t "Project Euler  24: ~a~%" (project-euler-024))
  (format t "Project Euler  25: ~a~%" (project-euler-025))
  (format t "Project Euler  26: ~a~%" (project-euler-026))
  (format t "Project Euler  27: ~a~%" (project-euler-027))
  (format t "Project Euler  28: ~a~%" (project-euler-028))
  (format t "Project Euler  29: ~a~%" (project-euler-029))
  (format t "Project Euler  30: ~a~%" (project-euler-030))
  (format t "Project Euler  31: ~a~%" (project-euler-031))
  (format t "Project Euler  32: ~a~%" (project-euler-032))
  (format t "Project Euler  33: ~a~%" (project-euler-033))
  (format t "Project Euler  34: ~a~%" (project-euler-034))
  (format t "Project Euler  35: ~a~%" (project-euler-035))
  (format t "Project Euler  36: ~a~%" (project-euler-036))
  (format t "Project Euler  37: ~a~%" (project-euler-037))
  (format t "Project Euler  38: ~a~%" (project-euler-038))
  (format t "Project Euler  39: ~a~%" (project-euler-039))
  (format t "Project Euler  40: ~a~%" (project-euler-040))
  (format t "Project Euler  41: ~a~%" (project-euler-041))
  (format t "Project Euler  42: ~a~%" (project-euler-042))
  (format t "Project Euler  43: ~a~%" (project-euler-043))
  (format t "Project Euler  44: ~a~%" (project-euler-044))
  (format t "Project Euler  45: ~a~%" (project-euler-045))
  (format t "Project Euler  46: ~a~%" (project-euler-046))
  (format t "Project Euler  47: ~a~%" (project-euler-047))
  (format t "Project Euler  48: ~a~%" (project-euler-048))
  (format t "Project Euler  49: ~a~%" (project-euler-049))
  (format t "Project Euler  50: ~a~%" (project-euler-050))
  (format t "Project Euler  51: ~a~%" (project-euler-051))
  (format t "Project Euler  52: ~a~%" (project-euler-052))
  (format t "Project Euler  53: ~a~%" (project-euler-053))
  (format t "Project Euler  54: ~a~%" (project-euler-054))
  (format t "Project Euler  55: ~a~%" (project-euler-055))
  (format t "Project Euler  56: ~a~%" (project-euler-056))
  (format t "Project Euler  57: ~a~%" (project-euler-057))
  (format t "Project Euler  58: ~a~%" (project-euler-058))
  (format t "Project Euler  59: ~a~%" (project-euler-059))
  (format t "Project Euler  60: ~a~%" (project-euler-060))
  (format t "Project Euler  61: ~a~%" (project-euler-061))
  (format t "Project Euler  62: ~a~%" (project-euler-062))
  (format t "Project Euler  63: ~a~%" (project-euler-063))
  (format t "Project Euler  64: ~a~%" (project-euler-064))
  (format t "Project Euler  65: ~a~%" (project-euler-065))
  (format t "Project Euler  66: ~a~%" (project-euler-066))
  (format t "Project Euler  67: ~a~%" (project-euler-067))
  (format t "Project Euler  68: ~a~%" (project-euler-068))
  (format t "Project Euler  69: ~a~%" (project-euler-069))
  (format t "Project Euler  70: ~a~%" (project-euler-070))
  (format t "Project Euler  71: ~a~%" (project-euler-071))
  (format t "Project Euler  72: ~a~%" (project-euler-072))
  (format t "Project Euler  73: ~a~%" (project-euler-073))
  (format t "Project Euler  74: ~a~%" (project-euler-074))
  (format t "Project Euler  75: ~a~%" (project-euler-075))
  (format t "Project Euler  80: ~a~%" (project-euler-080))
  (format t "Project Euler  81: ~a~%" (project-euler-081))
  (format t "Project Euler  89: ~a~%" (project-euler-089))
  (format t "Project Euler 254: ~a~%" (project-euler-254))
  (format t "Project Euler 684: ~a~%" (project-euler-684))

  (format t "Tupper Formula:~%")
  (tupper)

  (format t "~%Certificat:~%")
  (format t "  Josephus (41, every 3rd): ~a~%" (certificat-p33-4))

  (format t "~%Anecdotes Maths:~%")
  (format t "  2357 prime & digit-power sum prime: ~a~%" (anecdotes-maths-2357))
  (format t "  Smallest number with 17 divisors: ~a~%" (anecdotes-maths-65536-v1))
  (format t "  2^127 - 1 is prime: ~a~%" (anecdotes-maths-2-127-1-is-prime))
  (format t "  12345678910987654321 is prime: ~a~%" (anecdotes-maths-12345678910987654321-prime))
  (format t "  Prime factors of 13532385396179: ~a~%" (anecdotes-maths-13532385396179))

  (format t "~%Fermat's Library:~%")
  (format t "  33 as sum of three cubes: ~a~%" (fermat-library-33-as-sum-of-cubes))
  (format t "  42 as sum of three cubes: ~a~%" (fermat-library-42-as-sum-of-cubes))
  (format t "  19 prime & sum 19^0..19^18 prime: ~a~%" (fermat-library-19-31))
  (format t "  116! + 1 is prime: ~a~%" (fermat-library-116))
  (format t "  Digits in 9^9^9: ~a~%" (fermat-library-9-9-9))

  (format t "~%Devil Math Facts:~%")
  (format t "  Smallest cube with six 3's: ~a~%" (devil-math-fact-2))

  (format t "~%Ile Maths:~%")
  (format t "  553033 letter frequency score: ~a~%" (ilemaths-553033))
  (format t "  664857 smallest n with 5 's': ~a~%" (ilemaths-664857 5)))



;;; end
